import { buildModule } from './enhanceable.js';

export const {
  defaultNodeSize,
  treeFromValues,
  findBalancePoint,
  splitValues,
  collapses,
  nodeCollapses,
  nodeCanDonate,
  pop,
  push,
  addAt,
  isValidNode,
  assertValidNode,
  getValues,
  getSums,
  setValues,
  isLeafNode,
  traverse,
  getSize,
  findPath,
  getAt,
  replaceAt,
} = buildModule();
